### ISSUE TITLE
Is there a corresponding article?

### ISSUE THREAD

**Issue by Jennie777555** [qiongwu86/Digital-Twin-Vehicular-Edge-Computing-Network_Task-Offloading-and-Resource-Allocation#5]
I'm interested in the model and would like to learn about it. Is there a corresponding article?

**Comment by kkkkk1906** [comment]
Of course, this code corresponds to article "Digital Twin Vehicular Edge Computing Network: Task Offloading and Resource Allocation", which has been indexed by ICICSP2024, but has not yet been published. You can look it up on arxiv at: https://arxiv.org/pdf/2407.11310

**Comment by Jennie777555** [comment]
> 当然，这段代码对应了《数字孪生车载边缘计算网络：任务卸载和资源分配》一文，该文章已经被 ICICSP2024 检索，但尚未发布。您可以在 arxiv 上查找它：https://arxiv.org/pdf/2407.11310
